name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release:
            - Your changes description here
          draft: false
          prerelease: false

      - name: Send Telegram notification
        if: success() && steps.create_release.outputs.id != ''
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🚀 Рабочий процесс GitHub Actions завершен!
            📦 Репозиторий: ${{ github.repository }}
            🏷️ Ветка: ${{ github.ref_name }}
            ✅ Статус: ${{ job.status }}
            🎉 Новый релиз: ${{ github.ref }}
